repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: double-quote-string-fixer
        exclude: .py
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/prettier/prettier
    rev: "2.0.4"
    hooks:
      - id: prettier
