language: node_js
node_js:
  - "12.14.1"
cache:
  - npm: false
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
before_script:
  - curl https://pre-commit.com/install-local.py | python -
  - pre-commit install
addons:
  - sonarcloud:
    organization: "rgposadas"
    token:
      secure: $SONAR_TOKEN
script:
  - npm install -g expo-cli --loglevel=error
  - npm install --log-level=error
  - echo "fakeSecret" >> secrets.js
  - npm run supercheck-travis
  - npm test
  - sonar-scanner
