language: node_js
node_js:
  - "12.14.1"
cache:
  - npm: false
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
before_script:
  - curl https://pre-commit.com/install-local.py | python -
  - pre-commit install
script:
  - pre-commit run -a
  - npm run test
